//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAnalyserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressure
    {
        public int Internal_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Systolic { get; set; }
        public int Diastolic { get; set; }
        public int Pulse { get; set; }
    }
}
