//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAnalyserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int Internal_ID { get; set; }
        public string Activity { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int Distance { get; set; }
    }
}
