//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAnalyserDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthAnalyserEntities : DbContext
    {
        public HealthAnalyserEntities()
            : base("name=HealthAnalyserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SleepData> SleepData { get; set; }
        public DbSet<Exercise> Exercise { get; set; }
        public DbSet<BloodPressure> BloodPressure { get; set; }
        public DbSet<Weight> Weight { get; set; }
        public DbSet<WeightGoal> WeightGoal { get; set; }
    }
}
