//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAnalyserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightGoal
    {
        public int Internal_ID { get; set; }
        public int InitialValue { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    }
}
